FROM node:20

WORKDIR /app

COPY package.json .
COPY tsconfig.json .

RUN npm install

# Done after npm install so it doesn't re-create the same layers if the source code is changed 
COPY src ./src

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
