version: '3'
services:
  backend:
    build: ./App
    container_name: express
    image: shehabfahmy/konecta-task8-backend:latest
    ports:
      - "3000:3000"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: mydb
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
    networks:
      - app-tier
      - db-tier

  db:
    build: ./PostgreSQL
    container_name: postgres
    image: shehabfahmy/konecta-task8-db:latest
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    networks:
      - db-tier

networks:
  app-tier:
  db-tier:
