apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true   # allows direct access to host network
      hostPID: true       # allows access to host process IDs
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.6.1
        ports:
        - name: metrics
          containerPort: 9100
          hostPort: 9100   # expose metrics on the node's IP
        securityContext:
          privileged: true   # needed for some host metrics
